spring.application.name=api-gateway

server.port=8080

#user-service configuration
spring.cloud.gateway.server.webflux.routes[0].id=user-service-route
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/users/**



#product-service configuration
spring.cloud.gateway.server.webflux.routes[1].id=product-service-route
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/products/**
#spring.cloud.gateway.server.webflux.routes[1].filters[0].name=CircuitBreaker
#spring.cloud.gateway.server.webflux.routes[1].filters[0].args.name=productServiceCircuitBreaker
#spring.cloud.gateway.server.webflux.routes[1].filters[0].args.fallbackUri=forward:/fallback/products




